# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computational Social Affective Neuroscience
email: computationalsan@gmail.com
description: The Jekyll version of the Phantom theme by HTML5 UP.
baseurl: "computational-san.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: ljchang
twitter_username: lukejchang
# facebook_URL: andrewbanchich
# instagram_username: andrewbanchich
# dribbble_username: andrewbanchich
# 500px_username: andrewbanchich
# phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
